name: pdf

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build LaTex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: tobias-waslowski-cv.pdf
          path: main.pdf