name: pdf

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build LaTex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add main.pdf
          git commit -m "Update PDF"
          git push -u origin main